# Generated by Django 5.1.2 on 2024-11-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
